apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: unity-jenkinsx-poc
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "154453345249"
    project: unity-cs-recorderjmeter-test
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: jnbTestOrg
    repository: jx-poc-gke-vault
  - key: staging
  - key: production
  ingress:
    domain: 34.121.209.58.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: jnbpocbot
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: gs://logs-unity-jenkinsx-poc-46b45a7af9e9
  - name: reports
    url: gs://reports-unity-jenkinsx-poc-46b45a7af9e9
  - name: repository
    url: gs://repository-unity-jenkinsx-poc-46b45a7af9e9
  vault:
    bucket: vault-unity-jenkinsx-poc-46b45a7af9e9
    key: crypto-key-unity-jenkinsx-poc-46b45a7af9e9
    keyring: keyring-unity-jenkinsx-poc-46b45a7af9e9
    name: unity-jenkinsx-poc
    serviceAccount: unity-jenkinsx-poc-vt
  webhook: lighthouse
